server:
  port: 8082
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
  sentinel:
    enabled: true
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8091
      http-method-specify: true